# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: intall Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "16.X"
      - uses: pnpm/action-setup@v2.2.2
      - name: intall pnpm
        uses: pnpm/action-setup@v2.2.2
        with: 
          version: "7.5.X"
      - name: install dep
        run: pnpm install
      - name: build webApp
        run: pnpm build:webApp
      - name: deploy
        uses: appleboy/scp-action@v0.0.1
        with: 
          host: ${{ secrets.NAN_HOST }}
          key: ${{ secrets.NAN_PEM }}
          source: "./apps/@www/webApp"
          port: 22
          target: ${{secrets.NAN_TARGET }}
          
   
